ulysses/jury/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import show_dashboard, show_help, reload_evaluation, candidate_history, candidate_previous_steps


app_name = "jury"


urlpatterns = [
    url(r'^reload_evaluation/', reload_evaluation, name="reload_evaluation"),
    url(r'^dashboard/', show_dashboard, name="dashboard"),
    url(r'^help/(?P<competition_url>.+)', show_help, name="help"),
    url(r'^candidate-history/', candidate_history, name="candidate_history"),
    url(r'^candidate-previous-steps/', candidate_previous_steps, name="candidate_previous_steps"),
]

ulysses/jury/templates/jury/candidate_history.html
{% load i18n custom_filters profile_tags ulysses_utils static %}

<div class="candidate-content">
    <div class="row">
        <div class="col-md-12">
            <div class="content-links">
                {% if candidate and competition.allow_access_to_jury_history %}
                <a href="#" data-id="{{current_evaluation.id}}" class="candidate-link">Return to evaluation</a>
                {% endif %}
            </div>
            <div class="content-title">History</div>
        </div>
    </div>

{% if message %}<div class="message">{{ message }}</div>{% endif %}

   <div class="row">
       <div class="col-md-12">
           <div class="section">
               <div class="section-header">
                   <div class="section-header-title">Candidate informations</div>
                   <a class="fold"><img src="{% static 'icons/fold-minus.svg' %}" /></a>
                   <a class="unfold"><img src="{% static 'icons/fold-plus.svg' %}" /></a>
               </div>
               <div class="section-body">
                   <ul class="section-list">
                       {% with profile=candidate.composer.user|profile %}
                       <li>
                           <div class="section-item-label">Born</div>
                           {{ profile.birth_date }} {% if profile.age %}(age : {{ profile.age }}){% endif %}
                       </li>
                       <li>
                           <div class="section-item-label">Citizenship</div>
                           {{ profile.citizenship.name }}
                       </li>
                       {% if profile.website %}
                       <li>
                           <div class="section-item-label">Website</div>
                           <a target="_blank" href="{{ profile.website }}">{{ profile.website }}</a>
                       </li>
                       {% endif %}
                       {% endwith %}
                   </ul>
                </div>
           </div>

           {% if evaluations %}
                {% for evaluation in evaluations %}
                    <div class="section">
                        <div class="section-header">
                            <div class="section-header-title">{{ evaluation.competition_step }}</div>
                            <a class="fold"><img src="{% static 'icons/fold-minus.svg' %}" /></a>
                            <a class="unfold"><img src="{% static 'icons/fold-plus.svg' %}" /></a>
                        </div>
                        <div class="section-body">
                            <ul class="section-list">
                            {% for note in evaluation.get_notes %}
                                {% with max_value=note.maximum_value %}
                                 <li>
                                   {{ note.key }}: {{ note.interpreted_value }}{% if max_value %} / {{ max_value }}{% endif %}
                                 </li>
                                {% endwith %}
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endfor %}
           {% else %}
                <div class="section">
                    <div class="section-header">
                        <div class="section-header-title">No History</div>
                    </div>
                    <div class="section-body">
                    </div>
                </div>
           {% endif %}
       </div>
   </div>
</div>

ulysses/jury/templates/jury/candidate_previous_steps.html
{% load i18n custom_filters profile_tags ulysses_utils static %}

<div class="candidate-content">
    <div class="row">
        <div class="col-md-12">
            <div class="content-links">
                {% if candidate and competition.allow_access_to_jury_history %}
                <a href="#" data-id="{{current_evaluation.id}}" class="candidate-link">Return to evaluation</a>
                {% endif %}
            </div>
            <div class="content-title">{% trans "Previous steps" %}</div>
        </div>
    </div>

{% if message %}<div class="message">{{ message }}</div>{% endif %}

   <div class="row">
       <div class="col-md-12">
           <div class="section">
               <div class="section-header">
                   <div class="section-header-title">Candidate informations</div>
                   <a class="fold"><img src="{% static 'icons/fold-minus.svg' %}" /></a>
                   <a class="unfold"><img src="{% static 'icons/fold-plus.svg' %}" /></a>
               </div>
               <div class="section-body">
                   <ul class="section-list">
                       {% with profile=candidate.composer.user|profile %}
                       <li>
                           <div class="section-item-label">Born</div>
                           {{ profile.birth_date }} {% if profile.age %}(age : {{ profile.age }}){% endif %}
                       </li>
                       <li>
                           <div class="section-item-label">Citizenship</div>
                           {{ profile.citizenship.name }}
                       </li>
                       {% if profile.website %}
                       <li>
                           <div class="section-item-label">Website</div>
                           <a target="_blank" href="{{ profile.website }}">{{ profile.website }}</a>
                       </li>
                       {% endif %}
                       {% endwith %}
                   </ul>
                </div>
           </div>

           {% if previous_evaluations %}
                {% for evaluation in previous_evaluations %}
                    <div class="section">
                        <div class="section-header">
                            <div class="section-header-title">
                                {{ evaluation.competition_step.name }} / {{ evaluation.jury_member.name }}
                            </div>
                            <a class="fold"><img src="{% static 'icons/fold-minus.svg' %}" /></a>
                            <a class="unfold"><img src="{% static 'icons/fold-plus.svg' %}" /></a>
                        </div>
                        <div class="section-body">
                            <ul class="section-list">
                            {% for note in evaluation.get_notes %}
                                {% with max_value=note.maximum_value %}
                                 <li>
                                   {{ note.key }}: {{ note.interpreted_value }}{% if max_value %} / {{ max_value }}{% endif %}
                                 </li>
                                {% endwith %}
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endfor %}
           {% else %}
                <div class="section">
                    <div class="section-header">
                        <div class="section-header-title">{% trans "No previous evaluations" %}</div>
                    </div>
                    <div class="section-body">
                    </div>
                </div>
           {% endif %}
       </div>
   </div>
</div>

ulysses/jury/templates/jury/dashboard.html
<!DOCTYPE html>{% load i18n custom_filters ulysses_utils static %}
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="fr" lang="fr">
  <head>
    <meta charset="utf-8">
    <title>Ulysses - Jury</title>
    {% include "web/_favicon.html" %}
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- CSS -->
    <link href="{% static_vs 'bootstrap/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
    <link rel="stylesheet" href="{% static_vs 'jury/css/ulysse-jury.css' %}">
    <link rel="stylesheet" href="{% static_vs 'css/colorbox.css' %}" type="text/css" />
    <!-- end CSS-->
    <script type="text/javascript" src="{% static 'js/tiny_mce/tiny_mce.js' %}"></script>
    <script src="{% static 'js/AC_QuickTime.js' %}" language="javascript" type="text/javascript"> </script>
    <script src="{% static 'jquery/jquery-1.10.2.min.js' %}"></script>
    <script type="text/javascript" src="{% static_vs 'js/ulysses_tinymce.js' %}"></script>
    <script type="text/javascript" src="{% static_vs 'jury/js/dropdown.js' %}"></script>
    <script type="text/javascript" src="{% static_vs 'jury/js/dashboard.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'js/jquery.colorbox.js' %}"></script>
    <script type="text/javascript" src="{% static_vs 'js/colorbox.ulysses.js' %}"></script>
    <script>
	$(document).ready(function($) {
	    $("#main").dashboard();
	});
    </script>
    <style>
      textarea {width: 100%;}
    </style>
  </head>
  <body>{% with competition=active_competition_step.competition %}
    <div class="container-fluid container-full">

      <div class="row-header">
        <div class="row">
          <div class="col-sm-3">
            <a href="{% url 'jury:dashboard' %}">
              <img src="{{ STATIC_URL }}img/logo.gif" class="logo img-fluid" alt="Ulysses Administration">
            </a>
          </div>
          <div class="col-sm-5 dropdown">
            <div class="menu-dd">
              <span class="label">Evaluations</span>
              <div class="dropdown a-dd">
                <span>{% if active_competition_step %}{{ competition.title|custom_truncatechars:35 }} : {{ active_competition_step.name }}{% endif %}</span>
              </div>
              {% if other_competitions_steps %}
              <ul class="dropdown-menu">
                {% for step in other_competitions_steps %}
                <li><a href="?step={{ step.id }}">{{ step.competition.title|custom_truncatechars:35 }} : {{ step.name }}</a></li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>
          </div>
          <div  class="col-sm-4">
            <div class="menu-user">
              <span class="a-dd">Ulysses {{version}}</span>
              <span class="a-dd" href="#">Logged in as {% filter force_escape %}{{ user.first_name }} {{ user.last_name }}{% endfilter %}</span>
              <a class="a-dd" href="{% url 'logout' %}">Logout</a>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          {% if as_jury_member %}<!-- Jury member -->{% else %}
            <div class="not-jury-warning">
              You are not allowed to evaluate the members. Only jury members of this competition are allowed to evaluate.
            </div>
            <!-- Not Jury member -->
          {% endif %}
        </div>
      </div>

      <div class="row-content">
        <div class="row">
          <div class="col-md-3">
            <div class="content-aside">

            <div class="content-aside-header">
              {% if as_jury_member %}
              <div class="total-count {% if status_url == 'all' %}all-selected{% endif %}">
                <a href="?{% if step_filter %}{{ step_filter}}&{% endif %}status=all" class="all">
                  All candidates ({{ total_count }})
                </a>
              </div>
              {% endif %}
              {% if filter_form %}
              <div class="jury-filter-form">
                <form class="auto-submit" method="post">{% csrf_token %}
                  {{ filter_form }}
                </form>
              </div>
              {% endif %}

              {% if as_jury_member and active_competition_step %}
              <ul class="filter">
                <li class="{% if status_url == 'to_process' %}selected{% endif %}">
                  <a href="?{% if step_filter %}{{ step_filter}}&{% endif %}status=to_process">
                    <div class="evaluation-bullet to_process"></div> To evaluate ({{ to_evaluate_count }})
                  </a>
                </li>
                <li class="{% if status_url == 'in_progress' %}selected{% endif %}">
                  <a href="?{% if step_filter %}{{ step_filter}}&{% endif %}status=in_progress">
                    <div class="evaluation-bullet in_progress"></div> In progress ({{ in_progress_count }})
                  </a>
                </li>
                <li class="{% if status_url == 'completed' %}selected{% endif %}">
                  <a href="?{% if step_filter %}{{ step_filter}}&{% endif %}status=completed">
                    <div class="evaluation-bullet completed"></div> Evaluated ({{ evaluated_count }})
                  </a>
                </li>
              </ul>
              {% endif %}

              {% if candidate_attribute_jury_filter_values %}
              {% if evaluation_list %}
                <form class="auto-submit" method="post">{% csrf_token %}
                <input type="hidden" name="attribute_filter" value="{{ attribute_filter }}"></input>
                <span class="candidate-attribute-filter">
                    Filter by candidate {{ active_competition_step.candidate_attribute_jury_filter }} :
                    <select name="candidate-attribute" class="form-control">
                        {% for val in candidate_attribute_jury_filter_values %}
                        <option value="{{ val.id }}" {% if val.selected %} selected="selected" {% endif %}>
                            {{ val.name }}
                        </option>
                        {% endfor %}
                    </select>
                </span>
                </form>
              {% endif %}
              {% endif %}
            </div>

            {% comment %}
            <div class="content-aside-candidates-stats">
              {% if evaluation_stats %}
              <span>TOTAL</span>
              <span class="numb">{% for key,value in evaluation_stats.items %}{{ key }} : {{ value }}{% if not forloop.last %} | {% endif %}{% endfor %}</span>
              {% endif %}
            </div>
            {% endcomment %}

            <div class="content-aside-candidates">
              <ul class="candidates-list">
                {% for item in evaluation_list %}
                <li {% if candidate.id == item.evaluation.candidate.id %}class="active"{% endif %}>
                  <a
                      href="#" data-id="{{ item.id }}" data-next="{{ item.next }}" data-prev="{{ item.prev }}"
                      data-index="{{ item.index }}"
                      class="candidate-link"
                    >
                      {% if as_jury_member %}<div class="evaluation-bullet {{ item.evaluation.status.url }}"></div>{% endif %}
                      {% if competition.display_candidate_name %}
                          {{ item.evaluation.candidate.composer|custom_truncatechars:28 }}
                      {% else %}
                          {% blocktrans %}Anonymous Candidate # {% endblocktrans %}{{ item.evaluation.candidate.composer.id }}
                      {% endif %}
                    </a>
                    {% if as_jury_member %}<div class="candidate-summary">
                      {% for summary_item in item.evaluation.get_short_summary_items %}
                        <div class="candidate-summary-item">{{ summary_item }}</div>
                      {% endfor %}
                    </div>{% endif %}
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
          </div>
          <div class="col-md-9">
            <div class="main-col">
              {% if not evaluation_list %}
                <div class="candidate-content">
                    <div class="row">
                        <div class="col-md-12">
                          {% if is_filtered %}
                            <i>{% trans 'There is not participants for this filter' %}</i>
                          {% else %}
                            <i>{% trans 'There is not participants for this evaluation' %}</i>
                          {% endif %}
                        </div>
                    </div>
                </div>
              {% else %}
                {% include "jury/candidate.html" %}
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endwith %}</body>
</html>

ulysses/jury/templates/jury/help.html
{% extends "colorbox/popup_base.html" %}

{% load i18n %}

{% block extra_head %}
<style>
  .guidelines-popup-content {
    min-height: 200px;
    max-height: 600px;
    overflow-y: scroll;
  }
  @media (min-width: 768px) {
    .guidelines-popup-content {
      min-width: 400px;
    }
  }
</style>
<script type="text/javascript">

  $(document).bind('cbox_complete', function(){
  });
  $(document).bind('cbox_cleanup', function(){
  });
 </script>
{% endblock %}

{% block title %}{% trans "Jury guidelines" %}{% endblock %}

{% block popup_content %}
<div class="guidelines-popup-content">
<h2>{{ competition.title }} specific guidelines</h2>
{% autoescape off %}{{ competition.jury_guidelines }}{% endautoescape %}
</div>
{% endblock %}